package com.dybar.entity;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AuditTableHeader generated by hbm2java
 */
@Entity
@Table(name = "audit_table_header", schema = "public")
public class AuditTableHeader implements java.io.Serializable {

	private AuditTableHeaderId id;

	public AuditTableHeader() {
	}

	public AuditTableHeader(AuditTableHeaderId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "tableName", column = @Column(name = "table_name", nullable = false, length = 100)),
			@AttributeOverride(name = "tableDesc", column = @Column(name = "table_desc", length = 100)),
			@AttributeOverride(name = "creatorReferTo", column = @Column(name = "creator_refer_to", length = 100)) })
	public AuditTableHeaderId getId() {
		return this.id;
	}

	public void setId(AuditTableHeaderId id) {
		this.id = id;
	}

}
