package com.dybar.entity;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AuditLogSum generated by hbm2java
 */
@Entity
@Table(name = "audit_log_sum", schema = "public")
public class AuditLogSum implements java.io.Serializable {

	private AuditLogSumId id;

	public AuditLogSum() {
	}

	public AuditLogSum(AuditLogSumId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "id", precision = 65535, scale = 65531)),
			@AttributeOverride(name = "tableName", column = @Column(name = "table_name", length = 100)),
			@AttributeOverride(name = "typeAction", column = @Column(name = "type_action", length = 1)),
			@AttributeOverride(name = "pk", column = @Column(name = "pk", length = 100)),
			@AttributeOverride(name = "createDate", column = @Column(name = "create_date", length = 8)),
			@AttributeOverride(name = "creatorId", column = @Column(name = "creator_id", length = 20)) })
	public AuditLogSumId getId() {
		return this.id;
	}

	public void setId(AuditLogSumId id) {
		this.id = id;
	}

}
