package com.dybar.entity;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AuditLogSumId generated by hbm2java
 */
@Embeddable
public class AuditLogSumId implements java.io.Serializable {

	private BigDecimal id;
	private String tableName;
	private String typeAction;
	private String pk;
	private Date createDate;
	private String creatorId;

	public AuditLogSumId() {
	}

	public AuditLogSumId(BigDecimal id, String tableName, String typeAction, String pk, Date createDate,
			String creatorId) {
		this.id = id;
		this.tableName = tableName;
		this.typeAction = typeAction;
		this.pk = pk;
		this.createDate = createDate;
		this.creatorId = creatorId;
	}

	@Column(name = "id", precision = 65535, scale = 65531)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "table_name", length = 100)
	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	@Column(name = "type_action", length = 1)
	public String getTypeAction() {
		return this.typeAction;
	}

	public void setTypeAction(String typeAction) {
		this.typeAction = typeAction;
	}

	@Column(name = "pk", length = 100)
	public String getPk() {
		return this.pk;
	}

	public void setPk(String pk) {
		this.pk = pk;
	}

	@Column(name = "create_date", length = 8)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "creator_id", length = 20)
	public String getCreatorId() {
		return this.creatorId;
	}

	public void setCreatorId(String creatorId) {
		this.creatorId = creatorId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AuditLogSumId))
			return false;
		AuditLogSumId castOther = (AuditLogSumId) other;

		return ((this.getId() == castOther.getId())
				|| (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
				&& ((this.getTableName() == castOther.getTableName()) || (this.getTableName() != null
						&& castOther.getTableName() != null && this.getTableName().equals(castOther.getTableName())))
				&& ((this.getTypeAction() == castOther.getTypeAction()) || (this.getTypeAction() != null
						&& castOther.getTypeAction() != null && this.getTypeAction().equals(castOther.getTypeAction())))
				&& ((this.getPk() == castOther.getPk()) || (this.getPk() != null && castOther.getPk() != null
						&& this.getPk().equals(castOther.getPk())))
				&& ((this.getCreateDate() == castOther.getCreateDate()) || (this.getCreateDate() != null
						&& castOther.getCreateDate() != null && this.getCreateDate().equals(castOther.getCreateDate())))
				&& ((this.getCreatorId() == castOther.getCreatorId()) || (this.getCreatorId() != null
						&& castOther.getCreatorId() != null && this.getCreatorId().equals(castOther.getCreatorId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getTableName() == null ? 0 : this.getTableName().hashCode());
		result = 37 * result + (getTypeAction() == null ? 0 : this.getTypeAction().hashCode());
		result = 37 * result + (getPk() == null ? 0 : this.getPk().hashCode());
		result = 37 * result + (getCreateDate() == null ? 0 : this.getCreateDate().hashCode());
		result = 37 * result + (getCreatorId() == null ? 0 : this.getCreatorId().hashCode());
		return result;
	}

}
