package com.dybar.entity;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AuditLog generated by hbm2java
 */
@Entity
@Table(name = "audit_log", schema = "public")
public class AuditLog implements java.io.Serializable {

	private AuditLogId id;

	public AuditLog() {
	}

	public AuditLog(AuditLogId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "id", nullable = false, precision = 65535, scale = 65531)),
			@AttributeOverride(name = "tableName", column = @Column(name = "table_name", length = 100)),
			@AttributeOverride(name = "fieldName", column = @Column(name = "field_name", length = 100)),
			@AttributeOverride(name = "type", column = @Column(name = "type", length = 1)),
			@AttributeOverride(name = "pk", column = @Column(name = "pk", length = 0)),
			@AttributeOverride(name = "oldValue", column = @Column(name = "old_value", length = 0)),
			@AttributeOverride(name = "newValue", column = @Column(name = "new_value", length = 0)),
			@AttributeOverride(name = "createDate", column = @Column(name = "create_date", length = 8)),
			@AttributeOverride(name = "creatorId", column = @Column(name = "creator_id", length = 100)) })
	public AuditLogId getId() {
		return this.id;
	}

	public void setId(AuditLogId id) {
		this.id = id;
	}

}
