package com.dybar.entity;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AuditLogId generated by hbm2java
 */
@Embeddable
public class AuditLogId implements java.io.Serializable {

	private BigDecimal id;
	private String tableName;
	private String fieldName;
	private Character type;
	private String pk;
	private String oldValue;
	private String newValue;
	private Date createDate;
	private String creatorId;

	public AuditLogId() {
	}

	public AuditLogId(BigDecimal id) {
		this.id = id;
	}

	public AuditLogId(BigDecimal id, String tableName, String fieldName, Character type, String pk, String oldValue,
			String newValue, Date createDate, String creatorId) {
		this.id = id;
		this.tableName = tableName;
		this.fieldName = fieldName;
		this.type = type;
		this.pk = pk;
		this.oldValue = oldValue;
		this.newValue = newValue;
		this.createDate = createDate;
		this.creatorId = creatorId;
	}

	@Column(name = "id", nullable = false, precision = 65535, scale = 65531)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "table_name", length = 100)
	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	@Column(name = "field_name", length = 100)
	public String getFieldName() {
		return this.fieldName;
	}

	public void setFieldName(String fieldName) {
		this.fieldName = fieldName;
	}

	@Column(name = "type", length = 1)
	public Character getType() {
		return this.type;
	}

	public void setType(Character type) {
		this.type = type;
	}

	@Column(name = "pk", length = 0)
	public String getPk() {
		return this.pk;
	}

	public void setPk(String pk) {
		this.pk = pk;
	}

	@Column(name = "old_value", length = 0)
	public String getOldValue() {
		return this.oldValue;
	}

	public void setOldValue(String oldValue) {
		this.oldValue = oldValue;
	}

	@Column(name = "new_value", length = 0)
	public String getNewValue() {
		return this.newValue;
	}

	public void setNewValue(String newValue) {
		this.newValue = newValue;
	}

	@Column(name = "create_date", length = 8)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "creator_id", length = 100)
	public String getCreatorId() {
		return this.creatorId;
	}

	public void setCreatorId(String creatorId) {
		this.creatorId = creatorId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AuditLogId))
			return false;
		AuditLogId castOther = (AuditLogId) other;

		return ((this.getId() == castOther.getId())
				|| (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
				&& ((this.getTableName() == castOther.getTableName()) || (this.getTableName() != null
						&& castOther.getTableName() != null && this.getTableName().equals(castOther.getTableName())))
				&& ((this.getFieldName() == castOther.getFieldName()) || (this.getFieldName() != null
						&& castOther.getFieldName() != null && this.getFieldName().equals(castOther.getFieldName())))
				&& ((this.getType() == castOther.getType()) || (this.getType() != null && castOther.getType() != null
						&& this.getType().equals(castOther.getType())))
				&& ((this.getPk() == castOther.getPk()) || (this.getPk() != null && castOther.getPk() != null
						&& this.getPk().equals(castOther.getPk())))
				&& ((this.getOldValue() == castOther.getOldValue()) || (this.getOldValue() != null
						&& castOther.getOldValue() != null && this.getOldValue().equals(castOther.getOldValue())))
				&& ((this.getNewValue() == castOther.getNewValue()) || (this.getNewValue() != null
						&& castOther.getNewValue() != null && this.getNewValue().equals(castOther.getNewValue())))
				&& ((this.getCreateDate() == castOther.getCreateDate()) || (this.getCreateDate() != null
						&& castOther.getCreateDate() != null && this.getCreateDate().equals(castOther.getCreateDate())))
				&& ((this.getCreatorId() == castOther.getCreatorId()) || (this.getCreatorId() != null
						&& castOther.getCreatorId() != null && this.getCreatorId().equals(castOther.getCreatorId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getTableName() == null ? 0 : this.getTableName().hashCode());
		result = 37 * result + (getFieldName() == null ? 0 : this.getFieldName().hashCode());
		result = 37 * result + (getType() == null ? 0 : this.getType().hashCode());
		result = 37 * result + (getPk() == null ? 0 : this.getPk().hashCode());
		result = 37 * result + (getOldValue() == null ? 0 : this.getOldValue().hashCode());
		result = 37 * result + (getNewValue() == null ? 0 : this.getNewValue().hashCode());
		result = 37 * result + (getCreateDate() == null ? 0 : this.getCreateDate().hashCode());
		result = 37 * result + (getCreatorId() == null ? 0 : this.getCreatorId().hashCode());
		return result;
	}

}
