package com.dybar.entity;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AuditTableHeaderId generated by hbm2java
 */
@Embeddable
public class AuditTableHeaderId implements java.io.Serializable {

	private String tableName;
	private String tableDesc;
	private String creatorReferTo;

	public AuditTableHeaderId() {
	}

	public AuditTableHeaderId(String tableName) {
		this.tableName = tableName;
	}

	public AuditTableHeaderId(String tableName, String tableDesc, String creatorReferTo) {
		this.tableName = tableName;
		this.tableDesc = tableDesc;
		this.creatorReferTo = creatorReferTo;
	}

	@Column(name = "table_name", nullable = false, length = 100)
	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	@Column(name = "table_desc", length = 100)
	public String getTableDesc() {
		return this.tableDesc;
	}

	public void setTableDesc(String tableDesc) {
		this.tableDesc = tableDesc;
	}

	@Column(name = "creator_refer_to", length = 100)
	public String getCreatorReferTo() {
		return this.creatorReferTo;
	}

	public void setCreatorReferTo(String creatorReferTo) {
		this.creatorReferTo = creatorReferTo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AuditTableHeaderId))
			return false;
		AuditTableHeaderId castOther = (AuditTableHeaderId) other;

		return ((this.getTableName() == castOther.getTableName()) || (this.getTableName() != null
				&& castOther.getTableName() != null && this.getTableName().equals(castOther.getTableName())))
				&& ((this.getTableDesc() == castOther.getTableDesc()) || (this.getTableDesc() != null
						&& castOther.getTableDesc() != null && this.getTableDesc().equals(castOther.getTableDesc())))
				&& ((this.getCreatorReferTo() == castOther.getCreatorReferTo())
						|| (this.getCreatorReferTo() != null && castOther.getCreatorReferTo() != null
								&& this.getCreatorReferTo().equals(castOther.getCreatorReferTo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTableName() == null ? 0 : this.getTableName().hashCode());
		result = 37 * result + (getTableDesc() == null ? 0 : this.getTableDesc().hashCode());
		result = 37 * result + (getCreatorReferTo() == null ? 0 : this.getCreatorReferTo().hashCode());
		return result;
	}

}
