package com.dybar.entity;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * GroupPrivilege generated by hbm2java
 */
@Entity
@Table(name = "group_privilege", schema = "public")
public class GroupPrivilege implements java.io.Serializable {

	private GroupPrivilegeId id;

	public GroupPrivilege() {
	}

	public GroupPrivilege(GroupPrivilegeId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "modifiedOn", column = @Column(name = "modified_on", length = 8)),
			@AttributeOverride(name = "modifiedBy", column = @Column(name = "modified_by", length = 20)),
			@AttributeOverride(name = "createdOn", column = @Column(name = "created_on", length = 8)),
			@AttributeOverride(name = "createdBy", column = @Column(name = "created_by", length = 20)),
			@AttributeOverride(name = "groupId", column = @Column(name = "group_id", length = 20)),
			@AttributeOverride(name = "branchId", column = @Column(name = "branch_id", length = 10)),
			@AttributeOverride(name = "menuId", column = @Column(name = "menu_id", length = 20)),
			@AttributeOverride(name = "privilegeType", column = @Column(name = "privilege_type", length = 1)) })
	public GroupPrivilegeId getId() {
		return this.id;
	}

	public void setId(GroupPrivilegeId id) {
		this.id = id;
	}

}
