package com.dybar.entity;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GroupPrivilegeId generated by hbm2java
 */
@Embeddable
public class GroupPrivilegeId implements java.io.Serializable {

	private Date modifiedOn;
	private String modifiedBy;
	private Date createdOn;
	private String createdBy;
	private String groupId;
	private String branchId;
	private String menuId;
	private String privilegeType;

	public GroupPrivilegeId() {
	}

	public GroupPrivilegeId(Date modifiedOn, String modifiedBy, Date createdOn, String createdBy, String groupId,
			String branchId, String menuId, String privilegeType) {
		this.modifiedOn = modifiedOn;
		this.modifiedBy = modifiedBy;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.groupId = groupId;
		this.branchId = branchId;
		this.menuId = menuId;
		this.privilegeType = privilegeType;
	}

	@Column(name = "modified_on", length = 8)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "modified_by", length = 20)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "created_on", length = 8)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "created_by", length = 20)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "group_id", length = 20)
	public String getGroupId() {
		return this.groupId;
	}

	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}

	@Column(name = "branch_id", length = 10)
	public String getBranchId() {
		return this.branchId;
	}

	public void setBranchId(String branchId) {
		this.branchId = branchId;
	}

	@Column(name = "menu_id", length = 20)
	public String getMenuId() {
		return this.menuId;
	}

	public void setMenuId(String menuId) {
		this.menuId = menuId;
	}

	@Column(name = "privilege_type", length = 1)
	public String getPrivilegeType() {
		return this.privilegeType;
	}

	public void setPrivilegeType(String privilegeType) {
		this.privilegeType = privilegeType;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GroupPrivilegeId))
			return false;
		GroupPrivilegeId castOther = (GroupPrivilegeId) other;

		return ((this.getModifiedOn() == castOther.getModifiedOn()) || (this.getModifiedOn() != null
				&& castOther.getModifiedOn() != null && this.getModifiedOn().equals(castOther.getModifiedOn())))
				&& ((this.getModifiedBy() == castOther.getModifiedBy()) || (this.getModifiedBy() != null
						&& castOther.getModifiedBy() != null && this.getModifiedBy().equals(castOther.getModifiedBy())))
				&& ((this.getCreatedOn() == castOther.getCreatedOn()) || (this.getCreatedOn() != null
						&& castOther.getCreatedOn() != null && this.getCreatedOn().equals(castOther.getCreatedOn())))
				&& ((this.getCreatedBy() == castOther.getCreatedBy()) || (this.getCreatedBy() != null
						&& castOther.getCreatedBy() != null && this.getCreatedBy().equals(castOther.getCreatedBy())))
				&& ((this.getGroupId() == castOther.getGroupId()) || (this.getGroupId() != null
						&& castOther.getGroupId() != null && this.getGroupId().equals(castOther.getGroupId())))
				&& ((this.getBranchId() == castOther.getBranchId()) || (this.getBranchId() != null
						&& castOther.getBranchId() != null && this.getBranchId().equals(castOther.getBranchId())))
				&& ((this.getMenuId() == castOther.getMenuId()) || (this.getMenuId() != null
						&& castOther.getMenuId() != null && this.getMenuId().equals(castOther.getMenuId())))
				&& ((this.getPrivilegeType() == castOther.getPrivilegeType())
						|| (this.getPrivilegeType() != null && castOther.getPrivilegeType() != null
								&& this.getPrivilegeType().equals(castOther.getPrivilegeType())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getModifiedOn() == null ? 0 : this.getModifiedOn().hashCode());
		result = 37 * result + (getModifiedBy() == null ? 0 : this.getModifiedBy().hashCode());
		result = 37 * result + (getCreatedOn() == null ? 0 : this.getCreatedOn().hashCode());
		result = 37 * result + (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
		result = 37 * result + (getGroupId() == null ? 0 : this.getGroupId().hashCode());
		result = 37 * result + (getBranchId() == null ? 0 : this.getBranchId().hashCode());
		result = 37 * result + (getMenuId() == null ? 0 : this.getMenuId().hashCode());
		result = 37 * result + (getPrivilegeType() == null ? 0 : this.getPrivilegeType().hashCode());
		return result;
	}

}
