package com.dybar.entity;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MBranch generated by hbm2java
 */
@Entity
@Table(name = "m_branch", schema = "public")
public class MBranch implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private BigDecimal branchId;
	private Date modifiedOn;
	private String modifiedBy;
	private Date createdOn;
	private String createdBy;
	private String branchCode;
	private String branchName;
	private String description;
	private String activeStatus;
	private BigDecimal branchLevel;
	private String postalCode;

	public MBranch() {
	}

	public MBranch(BigDecimal branchId) {
		this.branchId = branchId;
	}

	public MBranch(BigDecimal branchId, Date modifiedOn, String modifiedBy, Date createdOn, String createdBy,
			String branchCode, String branchName, String description, String activeStatus, BigDecimal branchLevel,
			String postalCode) {
		this.branchId = branchId;
		this.modifiedOn = modifiedOn;
		this.modifiedBy = modifiedBy;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.branchCode = branchCode;
		this.branchName = branchName;
		this.description = description;
		this.activeStatus = activeStatus;
		this.branchLevel = branchLevel;
		this.postalCode = postalCode;
	}

//	@Column(name = "branch_id", unique = true, nullable = false, precision = 65535, scale = 65531)
	@Id
	@Column(name="branch_id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE,generator="m_branch_seq_id")
	@SequenceGenerator(name="m_branch_seq_id",sequenceName="m_branch_seq",allocationSize=1)
	public BigDecimal getBranchId() {
		return this.branchId;
	}

	public void setBranchId(BigDecimal branchId) {
		this.branchId = branchId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_on", length = 8)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "modified_by", length = 20)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 8)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "created_by", length = 20)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "branch_code", length = 20)
	public String getBranchCode() {
		return this.branchCode;
	}

	public void setBranchCode(String branchCode) {
		this.branchCode = branchCode;
	}

	@Column(name = "branch_name", length = 100)
	public String getBranchName() {
		return this.branchName;
	}

	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "active_status", length = 1)
	public String getActiveStatus() {
		return this.activeStatus;
	}

	public void setActiveStatus(String activeStatus) {
		this.activeStatus = activeStatus;
	}

	@Column(name = "branch_level", precision = 65535, scale = 65531)
	public BigDecimal getBranchLevel() {
		return this.branchLevel;
	}

	public void setBranchLevel(BigDecimal branchLevel) {
		this.branchLevel = branchLevel;
	}

	@Column(name = "postal_code", length = 10)
	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

}
