package com.dybar.entity;


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MCategory generated by hbm2java
 */
@Entity
@Table(name = "m_category", schema = "public")
public class MCategory implements Serializable {

	private static final long serialVersionUID = 1L;
	
	private BigDecimal categoryId;
	private Date modifiedOn;
	private String modifiedBy;
	private Date createdOn;
	private String createdBy;
	private String categoryType;
	private String categoryName;
	private String categoryCode;
	private String description;
	private BigDecimal size;
	private BigDecimal price;
	private BigDecimal discount;

	public MCategory() {
	}

	public MCategory(BigDecimal categoryId) {
		this.categoryId = categoryId;
	}

	public MCategory(BigDecimal categoryId, Date modifiedOn, String modifiedBy, Date createdOn, String createdBy,
			String categoryType, String categoryName, String categoryCode, String description, BigDecimal size,
			BigDecimal price, BigDecimal discount) {
		this.categoryId = categoryId;
		this.modifiedOn = modifiedOn;
		this.modifiedBy = modifiedBy;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.categoryType = categoryType;
		this.categoryName = categoryName;
		this.categoryCode = categoryCode;
		this.description = description;
		this.size = size;
		this.price = price;
		this.discount = discount;
	}

	@Id
	@Column(name="category_id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE,generator="m_category_seq_id")
	@SequenceGenerator(name="m_category_seq_id",sequenceName="m_category_seq",allocationSize=1)
//	@Column(name = "category_id", unique = true, nullable = false, precision = 65535, scale = 65531)
	public BigDecimal getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(BigDecimal categoryId) {
		this.categoryId = categoryId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_on", length = 8)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "modified_by", length = 20)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 8)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "created_by", length = 20)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "category_type", length = 10)
	public String getCategoryType() {
		return this.categoryType;
	}

	public void setCategoryType(String categoryType) {
		this.categoryType = categoryType;
	}

	@Column(name = "category_name")
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	@Column(name = "category_code", length = 10)
	public String getCategoryCode() {
		return this.categoryCode;
	}

	public void setCategoryCode(String categoryCode) {
		this.categoryCode = categoryCode;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "size", precision = 65535, scale = 65531)
	public BigDecimal getSize() {
		return this.size;
	}

	public void setSize(BigDecimal size) {
		this.size = size;
	}

	@Column(name = "price", precision = 65535, scale = 65531)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "discount", precision = 65535, scale = 65531)
	public BigDecimal getDiscount() {
		return this.discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

}
