package com.dybar.entity;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MDoctor generated by hbm2java
 */
@Entity
@Table(name = "m_doctor", schema = "public")
public class MDoctor implements java.io.Serializable {

	private BigDecimal doctorId;
	private Date modifiedOn;
	private String modifiedBy;
	private Date createdOn;
	private String createdBy;
	private String doctorName;
	private String doctorAddress;
	private String doctorEmail;
	private String doctorHandphone;
	private String doctorSip;
	private String doctorCode;

	public MDoctor() {
	}

	public MDoctor(BigDecimal doctorId) {
		this.doctorId = doctorId;
	}

	public MDoctor(BigDecimal doctorId, Date modifiedOn, String modifiedBy, Date createdOn, String createdBy,
			String doctorName, String doctorAddress, String doctorEmail, String doctorHandphone, String doctorSip,
			String doctorCode) {
		this.doctorId = doctorId;
		this.modifiedOn = modifiedOn;
		this.modifiedBy = modifiedBy;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.doctorName = doctorName;
		this.doctorAddress = doctorAddress;
		this.doctorEmail = doctorEmail;
		this.doctorHandphone = doctorHandphone;
		this.doctorSip = doctorSip;
		this.doctorCode = doctorCode;
	}

	@Id

	@Column(name = "doctor_id", unique = true, nullable = false, precision = 65535, scale = 65531)
	public BigDecimal getDoctorId() {
		return this.doctorId;
	}

	public void setDoctorId(BigDecimal doctorId) {
		this.doctorId = doctorId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_on", length = 8)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "modified_by", length = 20)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 8)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "created_by", length = 20)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "doctor_name")
	public String getDoctorName() {
		return this.doctorName;
	}

	public void setDoctorName(String doctorName) {
		this.doctorName = doctorName;
	}

	@Column(name = "doctor_address")
	public String getDoctorAddress() {
		return this.doctorAddress;
	}

	public void setDoctorAddress(String doctorAddress) {
		this.doctorAddress = doctorAddress;
	}

	@Column(name = "doctor_email")
	public String getDoctorEmail() {
		return this.doctorEmail;
	}

	public void setDoctorEmail(String doctorEmail) {
		this.doctorEmail = doctorEmail;
	}

	@Column(name = "doctor_handphone", length = 15)
	public String getDoctorHandphone() {
		return this.doctorHandphone;
	}

	public void setDoctorHandphone(String doctorHandphone) {
		this.doctorHandphone = doctorHandphone;
	}

	@Column(name = "doctor_sip", length = 20)
	public String getDoctorSip() {
		return this.doctorSip;
	}

	public void setDoctorSip(String doctorSip) {
		this.doctorSip = doctorSip;
	}

	@Column(name = "doctor_code", length = 20)
	public String getDoctorCode() {
		return this.doctorCode;
	}

	public void setDoctorCode(String doctorCode) {
		this.doctorCode = doctorCode;
	}

}
