package com.dybar.entity;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SyParameterlist generated by hbm2java
 */
@Entity
@Table(name = "sy_parameterlist", schema = "public")
public class SyParameterlist implements java.io.Serializable {

	private SyParameterlistId id;

	public SyParameterlist() {
	}

	public SyParameterlist(SyParameterlistId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "parametercode", column = @Column(name = "parametercode", nullable = false, length = 20)),
			@AttributeOverride(name = "parametername", column = @Column(name = "parametername", nullable = false, length = 100)),
			@AttributeOverride(name = "parametervalue", column = @Column(name = "parametervalue", nullable = false, length = 100)) })
	public SyParameterlistId getId() {
		return this.id;
	}

	public void setId(SyParameterlistId id) {
		this.id = id;
	}

}
