package com.dybar.entity;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SyParameterlistId generated by hbm2java
 */
@Embeddable
public class SyParameterlistId implements java.io.Serializable {

	private String parametercode;
	private String parametername;
	private String parametervalue;

	public SyParameterlistId() {
	}

	public SyParameterlistId(String parametercode, String parametername, String parametervalue) {
		this.parametercode = parametercode;
		this.parametername = parametername;
		this.parametervalue = parametervalue;
	}

	@Column(name = "parametercode", nullable = false, length = 20)
	public String getParametercode() {
		return this.parametercode;
	}

	public void setParametercode(String parametercode) {
		this.parametercode = parametercode;
	}

	@Column(name = "parametername", nullable = false, length = 100)
	public String getParametername() {
		return this.parametername;
	}

	public void setParametername(String parametername) {
		this.parametername = parametername;
	}

	@Column(name = "parametervalue", nullable = false, length = 100)
	public String getParametervalue() {
		return this.parametervalue;
	}

	public void setParametervalue(String parametervalue) {
		this.parametervalue = parametervalue;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SyParameterlistId))
			return false;
		SyParameterlistId castOther = (SyParameterlistId) other;

		return ((this.getParametercode() == castOther.getParametercode())
				|| (this.getParametercode() != null && castOther.getParametercode() != null
						&& this.getParametercode().equals(castOther.getParametercode())))
				&& ((this.getParametername() == castOther.getParametername())
						|| (this.getParametername() != null && castOther.getParametername() != null
								&& this.getParametername().equals(castOther.getParametername())))
				&& ((this.getParametervalue() == castOther.getParametervalue())
						|| (this.getParametervalue() != null && castOther.getParametervalue() != null
								&& this.getParametervalue().equals(castOther.getParametervalue())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getParametercode() == null ? 0 : this.getParametercode().hashCode());
		result = 37 * result + (getParametername() == null ? 0 : this.getParametername().hashCode());
		result = 37 * result + (getParametervalue() == null ? 0 : this.getParametervalue().hashCode());
		return result;
	}

}
