package com.dybar.entity;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TAppLetter generated by hbm2java
 */
@Entity
@Table(name = "t_app_letter", schema = "public")
public class TAppLetter implements java.io.Serializable {

	private BigDecimal appLetterId;
	private Date modifiedOn;
	private String modifiedBy;
	private Date createdOn;
	private String createdBy;
	private BigDecimal deposit;

	public TAppLetter() {
	}

	public TAppLetter(BigDecimal appLetterId) {
		this.appLetterId = appLetterId;
	}

	public TAppLetter(BigDecimal appLetterId, Date modifiedOn, String modifiedBy, Date createdOn, String createdBy,
			BigDecimal deposit) {
		this.appLetterId = appLetterId;
		this.modifiedOn = modifiedOn;
		this.modifiedBy = modifiedBy;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.deposit = deposit;
	}

	@Id

	@Column(name = "app_letter_id", unique = true, nullable = false, precision = 65535, scale = 65531)
	public BigDecimal getAppLetterId() {
		return this.appLetterId;
	}

	public void setAppLetterId(BigDecimal appLetterId) {
		this.appLetterId = appLetterId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_on", length = 8)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "modified_by", length = 20)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 8)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "created_by", length = 20)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "deposit", precision = 65535, scale = 65531)
	public BigDecimal getDeposit() {
		return this.deposit;
	}

	public void setDeposit(BigDecimal deposit) {
		this.deposit = deposit;
	}

}
