package com.dybar.entity;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TAppLetterDetail generated by hbm2java
 */
@Entity
@Table(name = "t_app_letter_detail", schema = "public")
public class TAppLetterDetail implements java.io.Serializable {

	private BigDecimal letterId;
	private Date modifiedOn;
	private String modifiedBy;
	private Date createdOn;
	private String createdBy;
	private BigDecimal appLetterId;
	private String letterCode;
	private String letterName;

	public TAppLetterDetail() {
	}

	public TAppLetterDetail(BigDecimal letterId) {
		this.letterId = letterId;
	}

	public TAppLetterDetail(BigDecimal letterId, Date modifiedOn, String modifiedBy, Date createdOn, String createdBy,
			BigDecimal appLetterId, String letterCode, String letterName) {
		this.letterId = letterId;
		this.modifiedOn = modifiedOn;
		this.modifiedBy = modifiedBy;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.appLetterId = appLetterId;
		this.letterCode = letterCode;
		this.letterName = letterName;
	}

	@Id

	@Column(name = "letter_id", unique = true, nullable = false, precision = 65535, scale = 65531)
	public BigDecimal getLetterId() {
		return this.letterId;
	}

	public void setLetterId(BigDecimal letterId) {
		this.letterId = letterId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_on", length = 8)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "modified_by", length = 20)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 8)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "created_by", length = 20)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "app_letter_id", precision = 65535, scale = 65531)
	public BigDecimal getAppLetterId() {
		return this.appLetterId;
	}

	public void setAppLetterId(BigDecimal appLetterId) {
		this.appLetterId = appLetterId;
	}

	@Column(name = "letter_code", length = 20)
	public String getLetterCode() {
		return this.letterCode;
	}

	public void setLetterCode(String letterCode) {
		this.letterCode = letterCode;
	}

	@Column(name = "letter_name")
	public String getLetterName() {
		return this.letterName;
	}

	public void setLetterName(String letterName) {
		this.letterName = letterName;
	}

}
