package com.dybar.entity;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TCashier generated by hbm2java
 */
@Entity
@Table(name = "t_cashier", schema = "public")
public class TCashier implements java.io.Serializable {

	private BigDecimal paymentId;
	private Date modifiedOn;
	private String modifiedBy;
	private Date createdOn;
	private String createdBy;
	private String paymentType;
	private String bankName;
	private String cardNo;
	private Date paymentDate;
	private BigDecimal totalBilling;
	private BigDecimal totalPayment;
	private BigDecimal depositValue;
	private String flagDeposit;

	public TCashier() {
	}

	public TCashier(BigDecimal paymentId) {
		this.paymentId = paymentId;
	}

	public TCashier(BigDecimal paymentId, Date modifiedOn, String modifiedBy, Date createdOn, String createdBy,
			String paymentType, String bankName, String cardNo, Date paymentDate, BigDecimal totalBilling,
			BigDecimal totalPayment, BigDecimal depositValue, String flagDeposit) {
		this.paymentId = paymentId;
		this.modifiedOn = modifiedOn;
		this.modifiedBy = modifiedBy;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.paymentType = paymentType;
		this.bankName = bankName;
		this.cardNo = cardNo;
		this.paymentDate = paymentDate;
		this.totalBilling = totalBilling;
		this.totalPayment = totalPayment;
		this.depositValue = depositValue;
		this.flagDeposit = flagDeposit;
	}

	@Id

	@Column(name = "payment_id", unique = true, nullable = false, precision = 65535, scale = 65531)
	public BigDecimal getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(BigDecimal paymentId) {
		this.paymentId = paymentId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_on", length = 8)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "modified_by", length = 20)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 8)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "created_by", length = 20)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "payment_type", length = 20)
	public String getPaymentType() {
		return this.paymentType;
	}

	public void setPaymentType(String paymentType) {
		this.paymentType = paymentType;
	}

	@Column(name = "bank_name")
	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	@Column(name = "card_no", length = 30)
	public String getCardNo() {
		return this.cardNo;
	}

	public void setCardNo(String cardNo) {
		this.cardNo = cardNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "payment_date", length = 8)
	public Date getPaymentDate() {
		return this.paymentDate;
	}

	public void setPaymentDate(Date paymentDate) {
		this.paymentDate = paymentDate;
	}

	@Column(name = "total_billing", precision = 65535, scale = 65531)
	public BigDecimal getTotalBilling() {
		return this.totalBilling;
	}

	public void setTotalBilling(BigDecimal totalBilling) {
		this.totalBilling = totalBilling;
	}

	@Column(name = "total_payment", precision = 65535, scale = 65531)
	public BigDecimal getTotalPayment() {
		return this.totalPayment;
	}

	public void setTotalPayment(BigDecimal totalPayment) {
		this.totalPayment = totalPayment;
	}

	@Column(name = "deposit_value", precision = 65535, scale = 65531)
	public BigDecimal getDepositValue() {
		return this.depositValue;
	}

	public void setDepositValue(BigDecimal depositValue) {
		this.depositValue = depositValue;
	}

	@Column(name = "flag_deposit", length = 1)
	public String getFlagDeposit() {
		return this.flagDeposit;
	}

	public void setFlagDeposit(String flagDeposit) {
		this.flagDeposit = flagDeposit;
	}

}
