package com.dybar.entity;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TExaminationTest generated by hbm2java
 */
@Entity
@Table(name = "t_examination_test", schema = "public")
public class TExaminationTest implements java.io.Serializable {

	private BigDecimal testId;
	private Date modifiedOn;
	private String modifiedBy;
	private Date createdOn;
	private String createdBy;
	private BigDecimal examId;
	private BigDecimal categoryId;
	private Date testDate;
	private String testNote;
	private String testPic;

	public TExaminationTest() {
	}

	public TExaminationTest(BigDecimal testId) {
		this.testId = testId;
	}

	public TExaminationTest(BigDecimal testId, Date modifiedOn, String modifiedBy, Date createdOn, String createdBy,
			BigDecimal examId, BigDecimal categoryId, Date testDate, String testNote, String testPic) {
		this.testId = testId;
		this.modifiedOn = modifiedOn;
		this.modifiedBy = modifiedBy;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.examId = examId;
		this.categoryId = categoryId;
		this.testDate = testDate;
		this.testNote = testNote;
		this.testPic = testPic;
	}

	@Id

	@Column(name = "test_id", unique = true, nullable = false, precision = 65535, scale = 65531)
	public BigDecimal getTestId() {
		return this.testId;
	}

	public void setTestId(BigDecimal testId) {
		this.testId = testId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_on", length = 8)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "modified_by", length = 20)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 8)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "created_by", length = 20)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "exam_id", precision = 65535, scale = 65531)
	public BigDecimal getExamId() {
		return this.examId;
	}

	public void setExamId(BigDecimal examId) {
		this.examId = examId;
	}

	@Column(name = "category_id", precision = 65535, scale = 65531)
	public BigDecimal getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(BigDecimal categoryId) {
		this.categoryId = categoryId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "test_date", length = 8)
	public Date getTestDate() {
		return this.testDate;
	}

	public void setTestDate(Date testDate) {
		this.testDate = testDate;
	}

	@Column(name = "test_note")
	public String getTestNote() {
		return this.testNote;
	}

	public void setTestNote(String testNote) {
		this.testNote = testNote;
	}

	@Column(name = "test_pic")
	public String getTestPic() {
		return this.testPic;
	}

	public void setTestPic(String testPic) {
		this.testPic = testPic;
	}

}
