package com.dybar.entity;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TExamination generated by hbm2java
 */
@Entity
@Table(name = "t_examination", schema = "public")
public class TExamination implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private BigDecimal examId;
	private Date modifiedOn;
	private String modifiedBy;
	private Date createdOn;
	private String createdBy;
	private BigDecimal petId;
	private String historyNote;
	private BigDecimal temperature;
	private BigDecimal weight;
	private BigDecimal pulseRate;
	private BigDecimal heartRate;
	private BigDecimal respRate;
	private String indexBody;
	private String note;
	private BigDecimal customerType;

	public TExamination() {
	}

	public TExamination(BigDecimal examId) {
		this.examId = examId;
	}

	public TExamination(BigDecimal examId, Date modifiedOn, String modifiedBy, Date createdOn, String createdBy,
			BigDecimal petId, String historyNote, BigDecimal temperature, BigDecimal weight, BigDecimal pulseRate,
			BigDecimal heartRate, BigDecimal respRate, String indexBody, String note) {
		this.examId = examId;
		this.modifiedOn = modifiedOn;
		this.modifiedBy = modifiedBy;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.petId = petId;
		this.historyNote = historyNote;
		this.temperature = temperature;
		this.weight = weight;
		this.pulseRate = pulseRate;
		this.heartRate = heartRate;
		this.respRate = respRate;
		this.indexBody = indexBody;
		this.note = note;
	}

//	@Id
//	@Column(name = "exam_id", unique = true, nullable = false, precision = 65535, scale = 65531)

	@Id
	@Column(name="exam_id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE,generator="t_examination_seq_id")
	@SequenceGenerator(name="t_examination_seq_id",sequenceName="t_examination_seq",allocationSize=1)
//	@Column(name = "category_id", unique = true, nullable = false, precision = 65535, scale = 65531)
	public BigDecimal getExamId() {
		return this.examId;
	}

	public void setExamId(BigDecimal examId) {
		this.examId = examId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_on", length = 8)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "modified_by", length = 20)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 8)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "created_by", length = 20)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "pet_id", precision = 65535, scale = 65531)
	public BigDecimal getPetId() {
		return this.petId;
	}

	public void setPetId(BigDecimal petId) {
		this.petId = petId;
	}

	@Column(name = "history_note")
	public String getHistoryNote() {
		return this.historyNote;
	}

	public void setHistoryNote(String historyNote) {
		this.historyNote = historyNote;
	}

	@Column(name = "temperature", precision = 65535, scale = 65531)
	public BigDecimal getTemperature() {
		return this.temperature;
	}

	public void setTemperature(BigDecimal temperature) {
		this.temperature = temperature;
	}

	@Column(name = "weight", precision = 65535, scale = 65531)
	public BigDecimal getWeight() {
		return this.weight;
	}

	public void setWeight(BigDecimal weight) {
		this.weight = weight;
	}

	@Column(name = "pulse_rate", precision = 65535, scale = 65531)
	public BigDecimal getPulseRate() {
		return this.pulseRate;
	}

	public void setPulseRate(BigDecimal pulseRate) {
		this.pulseRate = pulseRate;
	}

	@Column(name = "heart_rate", precision = 65535, scale = 65531)
	public BigDecimal getHeartRate() {
		return this.heartRate;
	}

	public void setHeartRate(BigDecimal heartRate) {
		this.heartRate = heartRate;
	}

	@Column(name = "resp_rate", precision = 65535, scale = 65531)
	public BigDecimal getRespRate() {
		return this.respRate;
	}

	public void setRespRate(BigDecimal respRate) {
		this.respRate = respRate;
	}

	@Column(name = "index_body", length = 5)
	public String getIndexBody() {
		return this.indexBody;
	}

	public void setIndexBody(String indexBody) {
		this.indexBody = indexBody;
	}

	@Column(name = "note")
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}
	
	@Column(name = "customer_type")
	public BigDecimal getCustomerType() {
		return customerType;
	}

	public void setCustomerType(BigDecimal customerType) {
		this.customerType = customerType;
	}

}
