package com.dybar.entity;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TPet generated by hbm2java
 */
@Entity
@Table(name = "t_pet", schema = "public")
public class TPet implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -510895365307077591L;
	private BigDecimal petId;
	private Date modifiedOn;
	private String modifiedBy;
	private Date createdOn;
	private String createdBy;
	private BigDecimal customerId;
	private BigDecimal doctorId;
	private String speciesId;
	private String petName;
	private String petSex;
	private Date petBirthdate;
	private BigDecimal petAge;
	private String breed;
	private String color;

	public TPet() {
	}

	public TPet(BigDecimal petId) {
		this.petId = petId;
	}

	public TPet(BigDecimal petId, Date modifiedOn, String modifiedBy, Date createdOn, String createdBy,
			BigDecimal customerId, BigDecimal doctorId, String speciesId, String petName, String petSex,
			Date petBirthdate, BigDecimal petAge, String breed, String color) {
		this.petId = petId;
		this.modifiedOn = modifiedOn;
		this.modifiedBy = modifiedBy;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.customerId = customerId;
		this.doctorId = doctorId;
		this.speciesId = speciesId;
		this.petName = petName;
		this.petSex = petSex;
		this.petBirthdate = petBirthdate;
		this.petAge = petAge;
		this.breed = breed;
		this.color = color;
	}

	@Id
	@Column(name="pet_id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE,generator="t_pet_seq_id")
	@SequenceGenerator(name="t_pet_seq_id",sequenceName="t_pet_seq",allocationSize=1)
//	@Column(name = "pet_id", unique = true, nullable = false, precision = 65535, scale = 65531)
	public BigDecimal getPetId() {
		return this.petId;
	}

	public void setPetId(BigDecimal petId) {
		this.petId = petId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_on", length = 8)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "modified_by", length = 20)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 8)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "created_by", length = 20)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "customer_id", precision = 65535, scale = 65531)
	public BigDecimal getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(BigDecimal customerId) {
		this.customerId = customerId;
	}

	@Column(name = "doctor_id", precision = 65535, scale = 65531)
	public BigDecimal getDoctorId() {
		return this.doctorId;
	}

	public void setDoctorId(BigDecimal doctorId) {
		this.doctorId = doctorId;
	}

	@Column(name = "species_id", length = 10)
	public String getSpeciesId() {
		return this.speciesId;
	}

	public void setSpeciesId(String speciesId) {
		this.speciesId = speciesId;
	}

	@Column(name = "pet_name", length = 256)
	public String getPetName() {
		return this.petName;
	}

	public void setPetName(String petName) {
		this.petName = petName;
	}

	@Column(name = "pet_sex", length = 5)
	public String getPetSex() {
		return this.petSex;
	}

	public void setPetSex(String petSex) {
		this.petSex = petSex;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "pet_birthdate", length = 8)
	public Date getPetBirthdate() {
		return this.petBirthdate;
	}

	public void setPetBirthdate(Date petBirthdate) {
		this.petBirthdate = petBirthdate;
	}

	@Column(name = "pet_age", precision = 65535, scale = 65531)
	public BigDecimal getPetAge() {
		return this.petAge;
	}

	public void setPetAge(BigDecimal petAge) {
		this.petAge = petAge;
	}

	@Column(name = "breed", length = 20)
	public String getBreed() {
		return this.breed;
	}

	public void setBreed(String breed) {
		this.breed = breed;
	}

	@Column(name = "color", length = 20)
	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

}
