package com.dybar.entity;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TTreatment generated by hbm2java
 */
@Entity
@Table(name = "t_treatment", schema = "public")
public class TTreatment implements java.io.Serializable {

	private BigDecimal treatmentId;
	private Date modifiedOn;
	private String modifiedBy;
	private Date createdOn;
	private String createdBy;
	private BigDecimal petId;
	private String treatmentPlan;
	private String recommendation;
	private Date reminder;

	public TTreatment() {
	}

	public TTreatment(BigDecimal treatmentId) {
		this.treatmentId = treatmentId;
	}

	public TTreatment(BigDecimal treatmentId, Date modifiedOn, String modifiedBy, Date createdOn, String createdBy,
			BigDecimal petId, String treatmentPlan, String recommendation, Date reminder) {
		this.treatmentId = treatmentId;
		this.modifiedOn = modifiedOn;
		this.modifiedBy = modifiedBy;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.petId = petId;
		this.treatmentPlan = treatmentPlan;
		this.recommendation = recommendation;
		this.reminder = reminder;
	}

	@Id

	@Column(name = "treatment_id", unique = true, nullable = false, precision = 65535, scale = 65531)
	public BigDecimal getTreatmentId() {
		return this.treatmentId;
	}

	public void setTreatmentId(BigDecimal treatmentId) {
		this.treatmentId = treatmentId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_on", length = 8)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "modified_by", length = 20)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 8)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "created_by", length = 20)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "pet_id", precision = 65535, scale = 65531)
	public BigDecimal getPetId() {
		return this.petId;
	}

	public void setPetId(BigDecimal petId) {
		this.petId = petId;
	}

	@Column(name = "treatment_plan")
	public String getTreatmentPlan() {
		return this.treatmentPlan;
	}

	public void setTreatmentPlan(String treatmentPlan) {
		this.treatmentPlan = treatmentPlan;
	}

	@Column(name = "recommendation", length = 20)
	public String getRecommendation() {
		return this.recommendation;
	}

	public void setRecommendation(String recommendation) {
		this.recommendation = recommendation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "reminder", length = 8)
	public Date getReminder() {
		return this.reminder;
	}

	public void setReminder(Date reminder) {
		this.reminder = reminder;
	}

}
