package com.dybar.entity;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TTreatmentDetail generated by hbm2java
 */
@Entity
@Table(name = "t_treatment_detail", schema = "public")
public class TTreatmentDetail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal treatmentDetailId;
	private Date modifiedOn;
	private String modifiedBy;
	private Date createdOn;
	private String createdBy;
	private BigDecimal treatmentId;
	private String treatmentType;
	private Date treatmentDate;
	private String note;
	private BigDecimal doctorId;
	private String receipt;

	public TTreatmentDetail() {
	}

	public TTreatmentDetail(BigDecimal treatmentDetailId) {
		this.treatmentDetailId = treatmentDetailId;
	}

	public TTreatmentDetail(BigDecimal treatmentDetailId, Date modifiedOn, String modifiedBy, Date createdOn,
			String createdBy, BigDecimal treatmentId, String treatmentType, Date treatmentDate, String note,
			BigDecimal doctorId, String receipt) {
		this.treatmentDetailId = treatmentDetailId;
		this.modifiedOn = modifiedOn;
		this.modifiedBy = modifiedBy;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.treatmentId = treatmentId;
		this.treatmentType = treatmentType;
		this.treatmentDate = treatmentDate;
		this.note = note;
		this.doctorId = doctorId;
		this.receipt = receipt;
	}

	@Id

	@Column(name = "treatment_detail_id", unique = true, nullable = false, precision = 65535, scale = 65531)
	public BigDecimal getTreatmentDetailId() {
		return this.treatmentDetailId;
	}

	public void setTreatmentDetailId(BigDecimal treatmentDetailId) {
		this.treatmentDetailId = treatmentDetailId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_on", length = 8)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "modified_by", length = 20)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 8)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "created_by", length = 20)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "treatment_id", precision = 65535, scale = 65531)
	public BigDecimal getTreatmentId() {
		return this.treatmentId;
	}

	public void setTreatmentId(BigDecimal treatmentId) {
		this.treatmentId = treatmentId;
	}

	@Column(name = "treatment_type", length = 20)
	public String getTreatmentType() {
		return this.treatmentType;
	}

	public void setTreatmentType(String treatmentType) {
		this.treatmentType = treatmentType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "treatment_date", length = 8)
	public Date getTreatmentDate() {
		return this.treatmentDate;
	}

	public void setTreatmentDate(Date treatmentDate) {
		this.treatmentDate = treatmentDate;
	}

	@Column(name = "note")
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "doctor_id", precision = 65535, scale = 65531)
	public BigDecimal getDoctorId() {
		return this.doctorId;
	}

	public void setDoctorId(BigDecimal doctorId) {
		this.doctorId = doctorId;
	}

	@Column(name = "receipt")
	public String getReceipt() {
		return this.receipt;
	}

	public void setReceipt(String receipt) {
		this.receipt = receipt;
	}

}
