package com.dybar.entity;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserHistory generated by hbm2java
 */
@Entity
@Table(name = "user_history", schema = "public")
public class UserHistory implements java.io.Serializable {

	private BigDecimal id;
	private String userId;
	private String activity;
	private String ipadress;
	private Date time;

	public UserHistory() {
	}

	public UserHistory(BigDecimal id) {
		this.id = id;
	}

	public UserHistory(BigDecimal id, String userId, String activity, String ipadress, Date time) {
		this.id = id;
		this.userId = userId;
		this.activity = activity;
		this.ipadress = ipadress;
		this.time = time;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, precision = 65535, scale = 65531)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "user_id", length = 20)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "activity", length = 20)
	public String getActivity() {
		return this.activity;
	}

	public void setActivity(String activity) {
		this.activity = activity;
	}

	@Column(name = "ipadress", length = 20)
	public String getIpadress() {
		return this.ipadress;
	}

	public void setIpadress(String ipadress) {
		this.ipadress = ipadress;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time", length = 8)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

}
