package com.dybar.entity;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", schema = "public")
public class Users implements java.io.Serializable {

	private String userId;
	private Date modifiedOn;
	private String modifiedBy;
	private Date createdOn;
	private String createdBy;
	private String password;
	private String userName;
	private String neverExpire;
	private Date expireDate;
	private String activeStatus;
	private String branchId;
	private Date lastLogin;
	private String loginStatus;
	private BigDecimal invalidPwdCount;

	public Users() {
	}

	public Users(String userId) {
		this.userId = userId;
	}

	public Users(String userId, Date modifiedOn, String modifiedBy, Date createdOn, String createdBy, String password,
			String userName, String neverExpire, Date expireDate, String activeStatus, String branchId, Date lastLogin,
			String loginStatus, BigDecimal invalidPwdCount) {
		this.userId = userId;
		this.modifiedOn = modifiedOn;
		this.modifiedBy = modifiedBy;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.password = password;
		this.userName = userName;
		this.neverExpire = neverExpire;
		this.expireDate = expireDate;
		this.activeStatus = activeStatus;
		this.branchId = branchId;
		this.lastLogin = lastLogin;
		this.loginStatus = loginStatus;
		this.invalidPwdCount = invalidPwdCount;
	}

	@Id

	@Column(name = "user_id", unique = true, nullable = false, length = 20)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_on", length = 8)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "modified_by", length = 20)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 8)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "created_by", length = 20)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "password", length = 0)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "user_name", length = 100)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "never_expire", length = 1)
	public String getNeverExpire() {
		return this.neverExpire;
	}

	public void setNeverExpire(String neverExpire) {
		this.neverExpire = neverExpire;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expire_date", length = 8)
	public Date getExpireDate() {
		return this.expireDate;
	}

	public void setExpireDate(Date expireDate) {
		this.expireDate = expireDate;
	}

	@Column(name = "active_status", length = 1)
	public String getActiveStatus() {
		return this.activeStatus;
	}

	public void setActiveStatus(String activeStatus) {
		this.activeStatus = activeStatus;
	}

	@Column(name = "branch_id", length = 10)
	public String getBranchId() {
		return this.branchId;
	}

	public void setBranchId(String branchId) {
		this.branchId = branchId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_login", length = 8)
	public Date getLastLogin() {
		return this.lastLogin;
	}

	public void setLastLogin(Date lastLogin) {
		this.lastLogin = lastLogin;
	}

	@Column(name = "login_status", length = 1)
	public String getLoginStatus() {
		return this.loginStatus;
	}

	public void setLoginStatus(String loginStatus) {
		this.loginStatus = loginStatus;
	}

	@Column(name = "invalid_pwd_count", precision = 65535, scale = 65531)
	public BigDecimal getInvalidPwdCount() {
		return this.invalidPwdCount;
	}

	public void setInvalidPwdCount(BigDecimal invalidPwdCount) {
		this.invalidPwdCount = invalidPwdCount;
	}

}
