package com.dybar.entity;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VExamination generated by hbm2java
 */
@Entity
@Table(name = "v_examination", schema = "public")
public class VExamination implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private BigDecimal examId;
	private String historyNote;
	private BigDecimal temperature;
	private BigDecimal weight;
	private BigDecimal pulseRate;
	private BigDecimal heartRate;
	private BigDecimal respRate;
	private String indexBody;
	private String note;
	private String customerType;
	private String customerTypeDesc;
	private BigDecimal petId;
	private BigDecimal customerId;
	private String customerName;
	private BigDecimal doctorId;
	private String doctorName;
	private String speciesId;
	private String species;
	private String petName;
	private String petSex;
	private String petSexDesc;
	private Date petBirthdate;
	private BigDecimal petAge;
	private String breed;
	private String color;
	
	public VExamination() {
	}
	
	public VExamination(BigDecimal examId) {
		this.examId = examId;
	}

	public VExamination(BigDecimal examId, String historyNote, BigDecimal temperature, BigDecimal weight,
			BigDecimal pulseRate, BigDecimal heartRate, BigDecimal respRate, String indexBody, String note,
			String customerType, String customerTypeDesc, BigDecimal petId, BigDecimal customerId, String customerName,
			BigDecimal doctorId, String doctorName, String speciesId, String species, String petName, String petSex,
			String petSexDesc, Date petBirthdate, BigDecimal petAge, String breed, String color) {
		this.examId = examId;
		this.historyNote = historyNote;
		this.temperature = temperature;
		this.weight = weight;
		this.pulseRate = pulseRate;
		this.heartRate = heartRate;
		this.respRate = respRate;
		this.indexBody = indexBody;
		this.note = note;
		this.customerType = customerType;
		this.customerTypeDesc = customerTypeDesc;
		this.petId = petId;
		this.customerId = customerId;
		this.customerName = customerName;
		this.doctorId = doctorId;
		this.doctorName = doctorName;
		this.speciesId = speciesId;
		this.species = species;
		this.petName = petName;
		this.petSex = petSex;
		this.petSexDesc = petSexDesc;
		this.petBirthdate = petBirthdate;
		this.petAge = petAge;
		this.breed = breed;
		this.color = color;
	}
	
	@Id
	
	@Column(name = "exam_id", precision = 65535, scale = 65531)
	public BigDecimal getExamId() {
		return this.examId;
	}

	public void setExamId(BigDecimal examId) {
		this.examId = examId;
	}

	@Column(name = "history_note")
	public String getHistoryNote() {
		return this.historyNote;
	}

	public void setHistoryNote(String historyNote) {
		this.historyNote = historyNote;
	}

	@Column(name = "temperature", precision = 65535, scale = 65531)
	public BigDecimal getTemperature() {
		return this.temperature;
	}

	public void setTemperature(BigDecimal temperature) {
		this.temperature = temperature;
	}

	@Column(name = "weight", precision = 65535, scale = 65531)
	public BigDecimal getWeight() {
		return this.weight;
	}

	public void setWeight(BigDecimal weight) {
		this.weight = weight;
	}

	@Column(name = "pulse_rate", precision = 65535, scale = 65531)
	public BigDecimal getPulseRate() {
		return this.pulseRate;
	}

	public void setPulseRate(BigDecimal pulseRate) {
		this.pulseRate = pulseRate;
	}

	@Column(name = "heart_rate", precision = 65535, scale = 65531)
	public BigDecimal getHeartRate() {
		return this.heartRate;
	}

	public void setHeartRate(BigDecimal heartRate) {
		this.heartRate = heartRate;
	}

	@Column(name = "resp_rate", precision = 65535, scale = 65531)
	public BigDecimal getRespRate() {
		return this.respRate;
	}

	public void setRespRate(BigDecimal respRate) {
		this.respRate = respRate;
	}

	@Column(name = "index_body", length = 5)
	public String getIndexBody() {
		return this.indexBody;
	}

	public void setIndexBody(String indexBody) {
		this.indexBody = indexBody;
	}

	@Column(name = "note")
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "customer_type", length = 5)
	public String getCustomerType() {
		return this.customerType;
	}

	public void setCustomerType(String customerType) {
		this.customerType = customerType;
	}

	@Column(name = "customer_type_desc")
	public String getCustomerTypeDesc() {
		return this.customerTypeDesc;
	}

	public void setCustomerTypeDesc(String customerTypeDesc) {
		this.customerTypeDesc = customerTypeDesc;
	}

	@Column(name = "pet_id", precision = 65535, scale = 65531)
	public BigDecimal getPetId() {
		return this.petId;
	}

	public void setPetId(BigDecimal petId) {
		this.petId = petId;
	}

	@Column(name = "customer_id", precision = 65535, scale = 65531)
	public BigDecimal getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(BigDecimal customerId) {
		this.customerId = customerId;
	}

	@Column(name = "customer_name")
	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	@Column(name = "doctor_id", precision = 65535, scale = 65531)
	public BigDecimal getDoctorId() {
		return this.doctorId;
	}

	public void setDoctorId(BigDecimal doctorId) {
		this.doctorId = doctorId;
	}

	@Column(name = "doctor_name")
	public String getDoctorName() {
		return this.doctorName;
	}

	public void setDoctorName(String doctorName) {
		this.doctorName = doctorName;
	}

	@Column(name = "species_id", length = 10)
	public String getSpeciesId() {
		return this.speciesId;
	}

	public void setSpeciesId(String speciesId) {
		this.speciesId = speciesId;
	}

	@Column(name = "species", length = 100)
	public String getSpecies() {
		return this.species;
	}

	public void setSpecies(String species) {
		this.species = species;
	}

	@Column(name = "pet_name", length = 256)
	public String getPetName() {
		return this.petName;
	}

	public void setPetName(String petName) {
		this.petName = petName;
	}

	@Column(name = "pet_sex", length = 5)
	public String getPetSex() {
		return this.petSex;
	}

	public void setPetSex(String petSex) {
		this.petSex = petSex;
	}

	@Column(name = "pet_sex_desc", length = 100)
	public String getPetSexDesc() {
		return this.petSexDesc;
	}

	public void setPetSexDesc(String petSexDesc) {
		this.petSexDesc = petSexDesc;
	}

	@Column(name = "pet_birthdate", length = 8)
	public Date getPetBirthdate() {
		return this.petBirthdate;
	}

	public void setPetBirthdate(Date petBirthdate) {
		this.petBirthdate = petBirthdate;
	}

	@Column(name = "pet_age", precision = 65535, scale = 65531)
	public BigDecimal getPetAge() {
		return this.petAge;
	}

	public void setPetAge(BigDecimal petAge) {
		this.petAge = petAge;
	}

	@Column(name = "breed", length = 20)
	public String getBreed() {
		return this.breed;
	}

	public void setBreed(String breed) {
		this.breed = breed;
	}

	@Column(name = "color", length = 20)
	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VExaminationId))
			return false;
		VExaminationId castOther = (VExaminationId) other;

		return ((this.getExamId() == castOther.getExamId()) || (this.getExamId() != null
				&& castOther.getExamId() != null && this.getExamId().equals(castOther.getExamId())))
				&& ((this.getHistoryNote() == castOther.getHistoryNote())
						|| (this.getHistoryNote() != null && castOther.getHistoryNote() != null
								&& this.getHistoryNote().equals(castOther.getHistoryNote())))
				&& ((this.getTemperature() == castOther.getTemperature())
						|| (this.getTemperature() != null && castOther.getTemperature() != null
								&& this.getTemperature().equals(castOther.getTemperature())))
				&& ((this.getWeight() == castOther.getWeight()) || (this.getWeight() != null
						&& castOther.getWeight() != null && this.getWeight().equals(castOther.getWeight())))
				&& ((this.getPulseRate() == castOther.getPulseRate()) || (this.getPulseRate() != null
						&& castOther.getPulseRate() != null && this.getPulseRate().equals(castOther.getPulseRate())))
				&& ((this.getHeartRate() == castOther.getHeartRate()) || (this.getHeartRate() != null
						&& castOther.getHeartRate() != null && this.getHeartRate().equals(castOther.getHeartRate())))
				&& ((this.getRespRate() == castOther.getRespRate()) || (this.getRespRate() != null
						&& castOther.getRespRate() != null && this.getRespRate().equals(castOther.getRespRate())))
				&& ((this.getIndexBody() == castOther.getIndexBody()) || (this.getIndexBody() != null
						&& castOther.getIndexBody() != null && this.getIndexBody().equals(castOther.getIndexBody())))
				&& ((this.getNote() == castOther.getNote()) || (this.getNote() != null && castOther.getNote() != null
						&& this.getNote().equals(castOther.getNote())))
				&& ((this.getCustomerType() == castOther.getCustomerType())
						|| (this.getCustomerType() != null && castOther.getCustomerType() != null
								&& this.getCustomerType().equals(castOther.getCustomerType())))
				&& ((this.getCustomerTypeDesc() == castOther.getCustomerTypeDesc())
						|| (this.getCustomerTypeDesc() != null && castOther.getCustomerTypeDesc() != null
								&& this.getCustomerTypeDesc().equals(castOther.getCustomerTypeDesc())))
				&& ((this.getPetId() == castOther.getPetId()) || (this.getPetId() != null
						&& castOther.getPetId() != null && this.getPetId().equals(castOther.getPetId())))
				&& ((this.getCustomerId() == castOther.getCustomerId()) || (this.getCustomerId() != null
						&& castOther.getCustomerId() != null && this.getCustomerId().equals(castOther.getCustomerId())))
				&& ((this.getCustomerName() == castOther.getCustomerName())
						|| (this.getCustomerName() != null && castOther.getCustomerName() != null
								&& this.getCustomerName().equals(castOther.getCustomerName())))
				&& ((this.getDoctorId() == castOther.getDoctorId()) || (this.getDoctorId() != null
						&& castOther.getDoctorId() != null && this.getDoctorId().equals(castOther.getDoctorId())))
				&& ((this.getDoctorName() == castOther.getDoctorName()) || (this.getDoctorName() != null
						&& castOther.getDoctorName() != null && this.getDoctorName().equals(castOther.getDoctorName())))
				&& ((this.getSpeciesId() == castOther.getSpeciesId()) || (this.getSpeciesId() != null
						&& castOther.getSpeciesId() != null && this.getSpeciesId().equals(castOther.getSpeciesId())))
				&& ((this.getSpecies() == castOther.getSpecies()) || (this.getSpecies() != null
						&& castOther.getSpecies() != null && this.getSpecies().equals(castOther.getSpecies())))
				&& ((this.getPetName() == castOther.getPetName()) || (this.getPetName() != null
						&& castOther.getPetName() != null && this.getPetName().equals(castOther.getPetName())))
				&& ((this.getPetSex() == castOther.getPetSex()) || (this.getPetSex() != null
						&& castOther.getPetSex() != null && this.getPetSex().equals(castOther.getPetSex())))
				&& ((this.getPetSexDesc() == castOther.getPetSexDesc()) || (this.getPetSexDesc() != null
						&& castOther.getPetSexDesc() != null && this.getPetSexDesc().equals(castOther.getPetSexDesc())))
				&& ((this.getPetBirthdate() == castOther.getPetBirthdate())
						|| (this.getPetBirthdate() != null && castOther.getPetBirthdate() != null
								&& this.getPetBirthdate().equals(castOther.getPetBirthdate())))
				&& ((this.getPetAge() == castOther.getPetAge()) || (this.getPetAge() != null
						&& castOther.getPetAge() != null && this.getPetAge().equals(castOther.getPetAge())))
				&& ((this.getBreed() == castOther.getBreed()) || (this.getBreed() != null
						&& castOther.getBreed() != null && this.getBreed().equals(castOther.getBreed())))
				&& ((this.getColor() == castOther.getColor()) || (this.getColor() != null
						&& castOther.getColor() != null && this.getColor().equals(castOther.getColor())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getExamId() == null ? 0 : this.getExamId().hashCode());
		result = 37 * result + (getHistoryNote() == null ? 0 : this.getHistoryNote().hashCode());
		result = 37 * result + (getTemperature() == null ? 0 : this.getTemperature().hashCode());
		result = 37 * result + (getWeight() == null ? 0 : this.getWeight().hashCode());
		result = 37 * result + (getPulseRate() == null ? 0 : this.getPulseRate().hashCode());
		result = 37 * result + (getHeartRate() == null ? 0 : this.getHeartRate().hashCode());
		result = 37 * result + (getRespRate() == null ? 0 : this.getRespRate().hashCode());
		result = 37 * result + (getIndexBody() == null ? 0 : this.getIndexBody().hashCode());
		result = 37 * result + (getNote() == null ? 0 : this.getNote().hashCode());
		result = 37 * result + (getCustomerType() == null ? 0 : this.getCustomerType().hashCode());
		result = 37 * result + (getCustomerTypeDesc() == null ? 0 : this.getCustomerTypeDesc().hashCode());
		result = 37 * result + (getPetId() == null ? 0 : this.getPetId().hashCode());
		result = 37 * result + (getCustomerId() == null ? 0 : this.getCustomerId().hashCode());
		result = 37 * result + (getCustomerName() == null ? 0 : this.getCustomerName().hashCode());
		result = 37 * result + (getDoctorId() == null ? 0 : this.getDoctorId().hashCode());
		result = 37 * result + (getDoctorName() == null ? 0 : this.getDoctorName().hashCode());
		result = 37 * result + (getSpeciesId() == null ? 0 : this.getSpeciesId().hashCode());
		result = 37 * result + (getSpecies() == null ? 0 : this.getSpecies().hashCode());
		result = 37 * result + (getPetName() == null ? 0 : this.getPetName().hashCode());
		result = 37 * result + (getPetSex() == null ? 0 : this.getPetSex().hashCode());
		result = 37 * result + (getPetSexDesc() == null ? 0 : this.getPetSexDesc().hashCode());
		result = 37 * result + (getPetBirthdate() == null ? 0 : this.getPetBirthdate().hashCode());
		result = 37 * result + (getPetAge() == null ? 0 : this.getPetAge().hashCode());
		result = 37 * result + (getBreed() == null ? 0 : this.getBreed().hashCode());
		result = 37 * result + (getColor() == null ? 0 : this.getColor().hashCode());
		return result;
	}

	
	

}
